-- P0 production observability, durable webhook processing, call lifecycle,
-- push-permission persistence, and invitation delivery state.

begin;

alter table public.billing_webhook_events
  add column if not exists received_at timestamptz not null default now(),
  add column if not exists processing_status text not null default 'pending',
  add column if not exists processing_error text,
  add column if not exists attempt_count integer not null default 0,
  add column if not exists last_attempt_at timestamptz;

alter table public.billing_webhook_events
  alter column processed_at drop not null,
  alter column processed_at drop default;

update public.billing_webhook_events
set processing_status = 'processed',
    received_at = coalesce(received_at, processed_at),
    attempt_count = greatest(attempt_count, 1),
    last_attempt_at = coalesce(last_attempt_at, processed_at)
where processed_at is not null;

alter table public.billing_webhook_events
  drop constraint if exists billing_webhook_events_processing_status_check;

alter table public.billing_webhook_events
  add constraint billing_webhook_events_processing_status_check
  check (processing_status in ('pending', 'processing', 'processed', 'ignored', 'failed'));

create index if not exists billing_webhook_events_status_received_idx
  on public.billing_webhook_events (processing_status, received_at desc);

alter table public.meeting_requests
  add column if not exists call_state text not null default 'idle',
  add column if not exists ring_expires_at timestamptz,
  add column if not exists connected_at timestamptz,
  add column if not exists last_call_event_at timestamptz;

alter table public.meeting_requests
  drop constraint if exists meeting_requests_call_state_check;

alter table public.meeting_requests
  add constraint meeting_requests_call_state_check
  check (call_state in (
    'idle', 'dialling', 'ringing', 'incoming', 'connecting', 'connected',
    'busy', 'declined', 'missed', 'cancelled', 'ended'
  ));

update public.meeting_requests
set call_state = case
  when status = 'declined' then 'declined'
  when status = 'cancelled' then 'cancelled'
  when status = 'completed' then 'ended'
  when status = 'expired' then 'missed'
  when status = 'accepted' and request_reason = 'Call now' then 'ringing'
  else 'idle'
end
where call_state = 'idle';

create table if not exists public.call_lifecycle_events (
  id bigint generated by default as identity primary key,
  meeting_request_id uuid references public.meeting_requests(id) on delete cascade,
  conversation_id uuid references public.conversations(id) on delete set null,
  actor_profile_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  call_state text not null,
  provider text not null default 'daily',
  status text not null default 'success',
  response_time_ms integer,
  error_code text,
  error_detail text,
  context jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  constraint call_lifecycle_events_state_check check (call_state in (
    'idle', 'dialling', 'ringing', 'incoming', 'connecting', 'connected',
    'busy', 'declined', 'missed', 'cancelled', 'ended'
  )),
  constraint call_lifecycle_events_status_check check (status in ('success', 'failure'))
);

alter table public.call_lifecycle_events enable row level security;

create index if not exists call_lifecycle_events_meeting_time_idx
  on public.call_lifecycle_events (meeting_request_id, occurred_at desc);

create index if not exists call_lifecycle_events_failure_time_idx
  on public.call_lifecycle_events (occurred_at desc)
  where status = 'failure';

create table if not exists public.service_health_events (
  id bigint generated by default as identity primary key,
  service text not null,
  operation text not null,
  status text not null,
  response_time_ms integer,
  error_code text,
  error_detail text,
  trace_id text,
  context jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  constraint service_health_events_service_check check (service in (
    'daily', 'stripe', 'supabase', 'authentication', 'realtime', 'email',
    'push', 'storage', 'database', 'edge_functions', 'analytics'
  )),
  constraint service_health_events_status_check check (status in ('success', 'failure'))
);

alter table public.service_health_events enable row level security;

create index if not exists service_health_events_service_time_idx
  on public.service_health_events (service, occurred_at desc);

create index if not exists service_health_events_failure_time_idx
  on public.service_health_events (occurred_at desc)
  where status = 'failure';

create table if not exists public.notification_preferences (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  permission_state text not null default 'default',
  prompt_state text not null default 'not_prompted',
  subscription_active boolean not null default false,
  last_prompted_at timestamptz,
  decided_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint notification_preferences_permission_check
    check (permission_state in ('default', 'granted', 'denied', 'unsupported')),
  constraint notification_preferences_prompt_check
    check (prompt_state in ('not_prompted', 'shown', 'dismissed', 'accepted', 'denied'))
);

alter table public.notification_preferences enable row level security;

grant select, insert, update on table public.notification_preferences to authenticated;

drop policy if exists "Profiles can view notification preferences" on public.notification_preferences;
create policy "Profiles can view notification preferences"
on public.notification_preferences
for select
to authenticated
using ((select auth.uid()) = profile_id);

drop policy if exists "Profiles can create notification preferences" on public.notification_preferences;
create policy "Profiles can create notification preferences"
on public.notification_preferences
for insert
to authenticated
with check ((select auth.uid()) = profile_id);

drop policy if exists "Profiles can update notification preferences" on public.notification_preferences;
create policy "Profiles can update notification preferences"
on public.notification_preferences
for update
to authenticated
using ((select auth.uid()) = profile_id)
with check ((select auth.uid()) = profile_id);

alter table public.club_staff_invites
  add column if not exists email_delivery_status text not null default 'pending',
  add column if not exists email_last_sent_at timestamptz,
  add column if not exists email_delivery_error text;

alter table public.club_staff_invites
  drop constraint if exists club_staff_invites_email_delivery_status_check;

alter table public.club_staff_invites
  add constraint club_staff_invites_email_delivery_status_check
  check (email_delivery_status in ('pending', 'sent', 'failed'));

commit;
