-- Durable Stripe webhook receipts (idempotent for databases that already have these columns).
alter table if exists public.billing_webhook_events
  add column if not exists received_at timestamptz not null default now(),
  add column if not exists processing_status text not null default 'received',
  add column if not exists processing_error text,
  add column if not exists attempt_count integer not null default 0,
  add column if not exists last_attempt_at timestamptz,
  add column if not exists processed_at timestamptz;

create index if not exists billing_webhook_events_processing_status_idx
  on public.billing_webhook_events (processing_status, received_at);

-- Versioned, explicit legal consent. Direct access stays service-role only.
create table if not exists public.legal_consents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text,
  terms_version text not null,
  privacy_version text not null,
  source text not null check (source in ('email_signup', 'oauth_signup')),
  accepted_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (user_id, terms_version, privacy_version)
);

alter table public.legal_consents enable row level security;
revoke all on table public.legal_consents from anon, authenticated;
revoke all on sequence public.legal_consents_id_seq from anon, authenticated;

create index if not exists legal_consents_user_accepted_idx
  on public.legal_consents (user_id, accepted_at desc);

create schema if not exists private;

create or replace function private.record_signup_legal_consent()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if coalesce((new.raw_user_meta_data ->> 'legal_consent')::boolean, false) then
    insert into public.legal_consents (
      user_id,
      email,
      terms_version,
      privacy_version,
      source,
      accepted_at
    ) values (
      new.id,
      new.email,
      '2026-08-08',
      '2026-08-08',
      'email_signup',
      now()
    )
    on conflict (user_id, terms_version, privacy_version) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists record_signup_legal_consent on auth.users;
create trigger record_signup_legal_consent
  after insert on auth.users
  for each row execute function private.record_signup_legal_consent();

-- Track the canonical origin that last refreshed a push subscription.
alter table if exists public.push_subscriptions
  add column if not exists site_origin text;

-- Anonymous bug reports are inserted only through the rate-limited server action.
create table if not exists public.bug_reports (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(message) between 1 and 4000),
  page_url text check (page_url is null or char_length(page_url) <= 2048),
  profile_id uuid references public.profiles(id) on delete set null,
  reporter_email text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.bug_reports enable row level security;
revoke all on table public.bug_reports from anon, authenticated;
revoke all on sequence public.bug_reports_id_seq from anon, authenticated;

create index if not exists bug_reports_created_at_idx
  on public.bug_reports (created_at desc);
create index if not exists bug_reports_profile_id_idx
  on public.bug_reports (profile_id)
  where profile_id is not null;
